name: owvision
description: Software system to record, archive, analyze and share your weather station's data with anyone!
version: 0.0.13
repository: https://github.com/open-weather-vision/owvision

environment:
    sdk: ^3.9.2

workspace:
    - daemon
    - recorder
    - shared
    - daemon/clients/daemon_client_dart
    - dashboard
    - builder
