// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WeatherStationsColumns holds the columns for the "weather_stations" table.
	WeatherStationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// WeatherStationsTable holds the schema information for the "weather_stations" table.
	WeatherStationsTable = &schema.Table{
		Name:       "weather_stations",
		Columns:    WeatherStationsColumns,
		PrimaryKey: []*schema.Column{WeatherStationsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WeatherStationsTable,
	}
)

func init() {
}
