openapi: 3.1.0
info:
  title: Daemon REST API
  version: 0.0.10
tags:
  - name: Token
  - name: Station
paths:
  /stations:
    get:
      operationId: Station_all
      description: Get all stations.
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherStation'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Station
      security:
        - BearerAuth: []
  /stations/{id}:
    get:
      operationId: Station_one
      description: Get one station and it's sensors.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationAndSensors'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Station
      security:
        - BearerAuth: []
  /stations/{id}/history:
    get:
      operationId: Station_history
      description: Get the history of one ore more sensors (in a specific interval).
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: from
          in: query
          required: false
          schema:
            type: string
            format: date-time
          explode: false
        - name: to
          in: query
          required: false
          schema:
            type: string
            format: date-time
          explode: false
        - name: sensors
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorHistory'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Station
      security:
        - BearerAuth: []
  /stations/{id}/live:
    get:
      operationId: Station_connect
      description: Connect to a station's live websocket.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '101':
          description: Informational
          headers:
            connection:
              required: true
              schema:
                type: string
                enum:
                  - Upgrade
            upgrade:
              required: true
              schema:
                type: string
                enum:
                  - websocket
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Station
      security:
        - BearerAuth: []
  /tokens:
    post:
      operationId: Token_generate
      description: Generates a new token. Only succeeds if you are authenticated using an admin token, or once using the init token `%12345678%`.
      parameters:
        - name: role
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/TokenRole'
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            text/plain:
              schema:
                type: string
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Token
      security:
        - BearerAuth: []
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
    ErrorCode:
      type: string
      enum:
        - unauthorized
        - notFound
        - internalError
        - badRequest
    HistoryRecord:
      type: object
      required:
        - createdAt
      properties:
        value:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
    Sensor:
      type: object
      required:
        - id
        - element
        - name
        - recordIntervalSeconds
        - historyIntervalSeconds
      properties:
        id:
          type: integer
          format: int64
        element:
          $ref: '#/components/schemas/SensorElement'
        name:
          type: string
        recordIntervalSeconds:
          type: integer
          format: int64
        historyIntervalSeconds:
          type: integer
          format: int64
    SensorElement:
      type: string
      enum:
        - precipationAccumulated
        - precipationRate
        - snowHeight
        - pressure
        - temperature
        - windSpeed
        - windDirection
        - humidity
        - weatherCode
    SensorHistory:
      type: object
      required:
        - sensorName
        - unitId
        - history
      properties:
        sensorName:
          type: string
        unitId:
          type: string
        history:
          type: array
          items:
            $ref: '#/components/schemas/HistoryRecord'
    StationAndSensors:
      type: object
      required:
        - info
        - sensors
      properties:
        info:
          $ref: '#/components/schemas/WeatherStation'
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/Sensor'
    TokenRole:
      type: string
      enum:
        - admin
        - recorder
        - viewer
    Versions:
      type: string
      enum:
        - 0.0.10
    WeatherStation:
      type: object
      required:
        - id
        - name
        - longitude
        - latitude
        - createdAt
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        createdAt:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
servers:
  - url: http://127.0.0.1:7070/api/v1
    variables: {}
  - url: https://0.0.0.0:8080/api/v1
    variables: {}
