// Generated content - do not change
export enum UnitId {
    humidity_hum_percent = "hum_percent",
    length_in = "in",
    length_ft = "ft",
    length_m = "m",
    length_cm = "cm",
    prec_rate_mmph = "mmph",
    prec_rate_inph = "inph",
    precipitation_inch = "inch",
    precipitation_lpm2 = "lpm2",
    precipitation_mm = "mm",
    pressure_hpa = "hpa",
    pressure_inhg = "inhg",
    temperature_fahrenheit = "fahrenheit",
    temperature_kelvin = "kelvin",
    temperature_celsius = "celsius",
    winddir_degrees = "degrees",
    winddir_radians = "radians",
    windspeed_bft = "bft",
    windspeed_kmh = "kmh",
    windspeed_kn = "kn",
    windspeed_mph = "mph",
    windspeed_ms = "ms",
    just_none = "none",
}
