// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"open-weather-vision.org/demon/ent/weatherstation"
)

// WeatherStation is the model entity for the WeatherStation schema.
type WeatherStation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WeatherStation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case weatherstation.FieldID:
			values[i] = new(sql.NullInt64)
		case weatherstation.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WeatherStation fields.
func (_m *WeatherStation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case weatherstation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case weatherstation.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WeatherStation.
// This includes values selected through modifiers, order, etc.
func (_m *WeatherStation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WeatherStation.
// Note that you need to call WeatherStation.Unwrap() before calling this method if this WeatherStation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WeatherStation) Update() *WeatherStationUpdateOne {
	return NewWeatherStationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WeatherStation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WeatherStation) Unwrap() *WeatherStation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WeatherStation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WeatherStation) String() string {
	var builder strings.Builder
	builder.WriteString("WeatherStation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// WeatherStations is a parsable slice of WeatherStation.
type WeatherStations []*WeatherStation
