// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// WeatherStation is the predicate function for weatherstation builders.
type WeatherStation func(*sql.Selector)
